name:                funlang
version:             0.1.0.0
github:              "github.com/eignnx/funlang"
license:             OtherLicense
author:              "eignnx"
maintainer:          "eignnx@gmail.com"
copyright:           "2021 eignnx@gmail.com"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/eignnx/funlang#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- mtl
- containers
- filepath
- process

library:
  source-dirs: src

executables:
  funlang-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - funlang

tests:
  funlang-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - funlang
